### ISSUE TITLE
Hello Matthew

### ISSUE THREAD

**Issue by Mansourali** [matthewrkula/AnimatedPathView#1]
I just wondering if you know how to make the animated path trace a word like in muzei project in this link https://github.com/romannurik/muzei?

thanks in advance

**Comment by funkthemonk** [comment]
Check out Path.getTextPath:
http://developer.android.com/reference/android/graphics/Paint.html

Or the answers here might help:
http://stackoverflow.com/questions/2149707/get-font-glyphs-as-vectors-manipulate-and-product-svg-or-bitmap

**Comment by Mansourali** [comment]
thanks man
